jobs:
  - job: macOS
    pool:
      vmImage: "macOS-10.15"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "10.x"
        displayName: "Install Node.js"
      - script: npm ci
        displayName: "npm ci"
      - script: gem install bundler
        displayName: "Install bundler"
      - script: bundle install
        displayName: "Install gems"
      - script: xcrun simctl list
        displayName: List simulators
      - script: bundle exec fastlane thetest
        displayName: "Test"
